import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import SideBar from "./dashboard/sidebar/sideBar/page"
import Nav from "./dashboard/nav/page"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <main className='xl:h-[100vh] flex overflow-hidden'>
          <div>
            <SideBar />
          </div>
          <div className='w-full'>
            <Nav />
            {children}
          </div>
        </main>
      </body>
    </html>
  )
}
